name: "WiCAN Add-On"
version: "1.0"
slug: "wican_addon"
description: "WiCAN add-on"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: "application"
boot: "auto"
options:
  device_ip: "192.168.1.100"
  interval_seconds: 2
schema:
  device_ip: str
  interval_seconds: int
